Applying the two ML classification techniques to the 4th senario (model2 Dataset3):

In [94]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

Applying K-mean:

In [95]:
X_train, X_test, y_train, y_test = train_test_split(features3.cpu().numpy(), all_labels2, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X_train)
pseudo_labels = kmeans.labels_

knn_classifier = KNeighborsClassifier(n_neighbors=3)
knn_classifier.fit(X_train, pseudo_labels)

knn_predictions = knn_classifier.predict(X_test)

knn_conf_matrix = confusion_matrix(y_test, knn_predictions)
knn_accuracy = accuracy_score(y_test, knn_predictions)
knn_precision = precision_score(y_test, knn_predictions, average='micro')
knn_recall = recall_score(y_test, knn_predictions, average='micro')

print("k-Nearest Neighbors Performance:")
print("Confusion Matrix:\n", knn_conf_matrix)
print("Accuracy:", knn_accuracy)
print("Precision:", knn_precision)
print("Recall:", knn_recall)


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


k-Nearest Neighbors Performance:
Confusion Matrix:
 [[  0 437   0]
 [317  63   0]
 [223 160   0]]
Accuracy: 0.0525
Precision: 0.0525
Recall: 0.0525


Applying SVM:

In [96]:
svm_classifier = SVC(kernel='linear', C=1.0)
svm_classifier.fit(X_train, y_train)

svm_predictions = svm_classifier.predict(X_test)

svm_conf_matrix = confusion_matrix(y_test, svm_predictions)
svm_accuracy = accuracy_score(y_test, svm_predictions)
svm_precision = precision_score(y_test, svm_predictions, average='micro')
svm_recall = recall_score(y_test, svm_predictions, average='micro')

print("\nSupport Vector Machine Performance:")
print("Confusion Matrix:\n", svm_conf_matrix)
print("Accuracy:", svm_accuracy)
print("Precision:", svm_precision)
print("Recall:", svm_recall)


Support Vector Machine Performance:
Confusion Matrix:
 [[437   0   0]
 [  0 378   2]
 [  0   0 383]]
Accuracy: 0.9983333333333333
Precision: 0.9983333333333333
Recall: 0.9983333333333333
